# kubectl create namespace lab
# kubectl create -f k8s-deployment.yaml -n lab
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: lab-deployment
  labels:
    app: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab
  template:
    metadata:
      labels:
        app: lab
    spec:
      securityContext: {}
      containers:
      - name: lab
        image: 192.168.56.1:5000/barkbay/k8s-app-lab:v0
        securityContext: {}
        ports:
        - containerPort: 8888
      nodeSelector:
        kubernetes.io/hostname: node-01
