# kubectl apply -f k8s-deployment.yaml -n lab
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: lab-java-deployment
  labels:
    app: lab-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-java
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: lab-java
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 1234
        fsGroup: 2000
      containers:
      - name: lab
        image: 192.168.56.1:5000/barkbay/k8s-app-lab:java-v0
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: "-XX:+PrintFlagsFinal"
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "384Mi"
            cpu: "2"
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
