# $ kubectl create -f leak-svc.yaml -n leak
# service "leak-service" created
kind: Service
apiVersion: v1
metadata:
  name: lab-java-service
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: lab-java
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: lab-java
  namespace: lab
spec:
  rules:
  - host: lab.minikube
    http:
      paths:
      - backend:
          serviceName: lab-java-service
          servicePort: 80
